# Site settings
title: "Visualisateur Poppy Ergo Jr"
description: "Visualisateur WebGL pour le robot Poppy Ergo Jr."

# Build settings
markdown: kramdown

include: [ "_pages" ]

exclude: [
  "Gemfile",
  "Gemfile.lock"
]

docs_url: "http://docs.poppy-project.org/en/getting-started/visualize.html"
ga_id: UA-44384879-4
